version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - fin-api
      - fin-web
      
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
      
  fin-api:
    image: sudoshmudo/fin-api:latest
    command: python app/main.py
    tty: true
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}"
    depends_on:
      - postgres
  
  fin-web:
    image: sudoshmudo/fin-web:latest
    restart: always
    
volumes:
  db-data:

      
