version: '3.7'
services:
  swag:
    image: ghcr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    volumes:
      - ./swag:/config
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - STAGING=${CERT_TESTING}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
    depends_on:
      - api
      - web
    restart: unless-stopped

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5444:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
      
  api:
    image: sudoshmudo/fin-api:latest
    command: python app/main.py
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}"
    depends_on:
      - postgres
  
  web:
    image: sudoshmudo/fin-web:latest
    restart: always
    
volumes:
  db-data:

      
